language: elixir
matrix:
  include:
    - otp_release: 18.0
      elixir: 1.2
    - otp_release: 20.0
      elixir: 1.4
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq imagemagick
